version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.9.0
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Apply rubocop
          command: |
            rubocop --format simple --only Layout --debug
      - run:
          name: Update all measures
          command: |
            rake update_measures
      - run: 
          name: Regenerate test osms
          command: |
            rake test:regenerate_osms
      - run: 
          name: Run all unit tests
          command: |
            rake test:unit_tests
      - run:
          name: Run all regression tests
          command: |
            rake test:regression_tests
      - store_artifacts:
            path: workflows/results/results.csv
            destination: example_osws.csv
      - store_artifacts:
            path: test/test_measures_osw/results/results.csv
            destination: measures_osws.csv
      - store_artifacts:
            path: test/test_measures_osw/buildstock.csv
            destination: buildstock.csv
      - store_artifacts:
            path: resources/measures/ResidentialScheduleGenerator/tests/output/test_sweep_building_ids_and_num_occupants
            destination: schedules
  docs:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Build documentation
          command: |
            cd docs/read_the_docs
            pip install -r requirements.txt
            make html
      - store_artifacts:
            path: docs/read_the_docs/build
            destination: readthedocs
workflows:
  version: 2
  commit:
    jobs:
      - build
      - docs:
          requires:
            - build
